### ISSUE TITLE
Miranda can't convert my profile database to new one

### ISSUE THREAD

**Issue by johny-mnemonic** [miranda-ng/miranda-ng#1326]
### Expected behavior
After upgrading to 0.95.8 Miranda should convert profile database from mmap to mdbx.

### Actual behavior
Miranda asks on each start whether it should convert the old database to new format, but when I press yes, it then produce error about being unable to open profile database. Old database file is not even touched and no database file backup is created.

### Does it work in stable version?
When I reverted back to 0.95.7 by copying files from \Plugin Updates\Backups\, Miranda happily reads the old database and everything works.

### Steps to reproduce that behavior
I didn't do anything specific. Miranda-NG just asked to be restarted after updating of 39 files. So I did just that and after restart, it asked, whether it should upgrade the database to new version. Rest is described above.
I should probably mention, that my database was created by conversion from old Miranda to Miranda-NG and it dates back to 2002 I guess.

I would love to provide any logs, but I have no clue how to force Miranda to produce them. There are no crash logs or any other logs from this. It looks like it tries to convert the database, fails at that, but still continues by trying to open it with mdbx driver, which then reports it has unreadable structure. Then it closes without crashing or producing logs...

**Comment by dartraiden** [comment]
Very similar to #1323

**Comment by georgehazan** [comment]
is that possible that either profile or directory name might contain non-printable / Unicode symbols?

**Comment by johny-mnemonic** [comment]
My OS is in Czech, so it has lot of non-ascii chars, but shouldn't contain any non-printable / Unicode symbols. Either way, there are none in the path, as I am using simple ascii username.
c:\Users\USER_NAME\Dropbox\Programy\Miranda\Profile\dbase-v6.8\dbase-v6.8.dat

**Comment by dartraiden** [comment]
Please revert to 0.95.7, use PluginUpdater and test again; we fixed some "Unknown format" related bug.

**Comment by jl452** [comment]
for me bug not fixed at right now, but i on wine 3.7+ubuntu 17.10
russian message https://forum.miranda-ng.org/index.php?topic=5473.msg21651#msg21651

**Comment by jl452** [comment]
empty fail_on_convert dat-file https://forum.miranda-ng.org/index.php?topic=5473.msg21654#msg21654

**Comment by johny-mnemonic** [comment]
Still behaves the same. 
I reverted to 0.95.7 and then used PluginUpdater to upgrade again. Ended with same error like described in OP.

**Comment by johny-mnemonic** [comment]
Any news on this one? I just tried to update to latest Miranda NG (0.95.8) and ended with the same error as described in OP.
Conversion from old database is obviously still not working:-(

**Comment by georgehazan** [comment]
@johny-mnemonic I'm afraid that the only choice in this case is to send your profile to me via email (ghazan at miranda point org), zipped

**Comment by Razunter** [comment]
This shouldn't be closed. I don't want to send my DB to anyone and this issue isn't fixed yet.

**Comment by georgehazan** [comment]
how else can I understand what's going on? network log subsystem isn't initialized when a database is getting loaded, so the only choice is the debugging under Visual Studio via TeamViewer. are you ready?

**Comment by johny-mnemonic** [comment]
@georgehazan I agree with @Razunter, there is no solution offered here, so why closing this?
There must be a way to manually execute the database conversion and log the results. Why you want us to send you our databases? :-O
Mine contains quite a few sensitive info.

**Comment by georgehazan** [comment]
@johny-mnemonic what about the second part of my message? can you try to create the empty new profile on your old Miranda and convert it using the nightly build?

**Comment by johny-mnemonic** [comment]
@georgehazan sure, I will definitely do that.
I am running it on Windows 10 natively, so it shouldn't be caused by OS though...

**Comment by johny-mnemonic** [comment]
@georgehazan I tried to create new profile and then upgrade Miranda to latest version delivered by updater.
Everything worked without an issue...as expected;-)
So the trouble is definitely inside my old big database, that accumulated all sorts of changes through all these years.
I opened database editor and I can for example see, that some status messages for contacts are fine, and some has obviously broken code page, as they do not display non-english characters correctly. Issues like this could be minor, but could also crash the library doing conversion...hard to tell without any kind of log from that conversion.

**Comment by georgehazan** [comment]
@johny-mnemonic send me please the hex dump (from FAR, TC, HxD etc) of first 256 bytes of your database.

**Comment by johny-mnemonic** [comment]
@georgehazan 
[dbase_hxd_256b.txt](https://github.com/miranda-ng/miranda-ng/files/2342262/dbase_hxd_256b.txt)

**Comment by georgehazan** [comment]
yes, format is correct. have you tried to run dbchecker over the old profile on 0.95.7? second, how big is your old profile? if it's bigger than 200-250MB, 32-bit Miranda won't open it, only 64-bit Miranda will

**Comment by georgehazan** [comment]
@johny-mnemonic check please if there's a .BAK file in the same folder with your .DAT file, if it exists, remove it and try again

**Comment by johny-mnemonic** [comment]
@georgehazan thanks a lot!
I am on Miranda NG 95.9 with converted database.

I don't know whether previous failures were caused by the presence of that .BAK file or whether you fixed something in latest build, but it now converted just fine.

**Comment by dartraiden** [comment]
> I don't know whether previous failures were caused by the presence of that .BAK file
This.

v0.95.8 moves mmap database to .bak. But you already had a .bak file there, so Miranda cannot move mmap to bak and cannot start conversion.

**Comment by johny-mnemonic** [comment]
@dartraiden OK. That bak file was most probably from the first attempt of converting the database. File timestamp at least points that way. 
So maybe the original issue was fixed long time ago, but because that first failed conversion left bak file after it, consequent trials all silently failed:-(
I would say that the take from this is, you should never swallow breaking error message. It is always better to show it to the user and let it report that issue...

**Comment by georgehazan** [comment]
@johny-mnemonic mea culpa :) I've written the standard code that logs everything into the network log, taking no care about the fact that this log is not initialized yet in this time :)

**Comment by johny-mnemonic** [comment]
@georgehazan yeah, I know this moment, when you search for the author of obvious nonsense you just found and git blame points at you :-D
Anyway, thanks for help!
