### ISSUE TITLE
Kill ImportTXT in favour to Import

### ISSUE THREAD

**Issue by dartraiden** [miranda-ng/miranda-ng#1490]
We already implement some ImportTXT features in Import. This ticket just for tracking purposes.

**Comment by georgehazan** [comment]
we need two more features to port, according to @LittleVulpix :
- ability to process messages in any text format (I would prefer json);
- ability to discard duplicates

**Comment by RathaWynter** [comment]
Does Import now handle importing individual text histories on demand via mContacts?

**Comment by georgehazan** [comment]
Yes, for about a month

**Comment by georgehazan** [comment]
MsgExport now is able to write history as JSON, and Import can read that JSON.

**Comment by georgehazan** [comment]
ok, we can check dups as well now

**Comment by LittleVulpix** [comment]
@georgehazan can we also _not_ check dups? I.e. is this option a toggle?

**Comment by georgehazan** [comment]
a checkbox, to be concrete

**Comment by georgehazan** [comment]
@LittleVulpix so we're waiting for your response. If you signal that both Msg_export & Import work properly with JSON & mContacts, we could kill ImportTXT

**Comment by LittleVulpix** [comment]
@georgehazan tested, observations:

1) unless the latest build is not yet compiled, I do not see the option to disable skipping duplicates
2) Import doesn't state it can import text as well; it simply immediately prompts you for a file to load, moreover the file picker only shows dat filepicker option (you have to select "all" to load up text files)
2) MsgExport does not export to json with human-readable timestamps (i.e. it ignores the timestamp setting for the other export). If I am to be able to use this fulltime, it should be human readable (so I don't need to use the "regular" text export as well at the same time)
3) for some reason it discards every last character on import (the exported json is "lol", imported text is "lo")
4) when I tried exporting imported history again, it exports empty messages (both in txt mode and in json mode) which is very strange.

**Comment by georgehazan** [comment]
1. mmm, perhaps. pushed a new build to server
2. Import cannot import a text file at all, it imports mContacts / JSON / dat profile.
3. Msg_Export uses timeStamp, yes. why should it use a human readable format, if it alsready has the required data?
4. let's wait for a new build.
5. same as 4

**Comment by georgehazan** [comment]
2. is already fixed in a new version

**Comment by LittleVulpix** [comment]
Okay, checked the updated version.

1) as noted before it does not import last character of every message.
2) my miranda crashes silently during import. Generates a crash log but it's 0-size. No freeze, the process just disappears.
3) Human-readable timestamps on json export please :))

**Comment by LittleVulpix** [comment]
My miranda crashed on startup with msgexport in json mode:

```
Miranda Crash Report from 15 Aug 2018 18:43:43. Crash Dumper v.0.1.0.2

Likely cause of the crash plugin: Message export

Exception: Access Violation at address 00000000127811AD. Reading from address 0000000000000000.

Stack Trace:
---------------------------------------------------------------
00000000127811AD (libjson 0000000012780000): c:\vs2017\vc\tools\msvc\14.15.26726\include\xstring (2185): std::basic_string<char,std::char_traits<char>,std::allocator<char> >::basic_string<char,std::char_traits<char>,std::allocator<char> >
00000000127889B3 (libjson 0000000012780000): w:\miranda-build\libs\libjson\src\jsonnode.cpp (57): JSONNode::JSONNode
00000000193D9E67 (Msg_Export 00000000193D0000): w:\miranda-build\plugins\msg_export\src\utils.cpp (724): ExportDBEventInfo
00000000193DC63E (Msg_Export 00000000193D0000): w:\miranda-build\plugins\msg_export\src\utils.cpp (1115): bExportEvent
00000000193DD05E (Msg_Export 00000000193D0000): w:\miranda-build\plugins\msg_export\src\utils.cpp (1094): nExportEvent
0000000012AB51C2 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\modules.cpp (242): CallHookSubscribers
0000000012AB576C (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\modules.cpp (292): NotifyEventHooks
0000000017BD5F82 (Dbx_mdbx 0000000017BD0000): w:\miranda-build\plugins\dbx_mdbx\src\dbevents.cpp (143): CDbxMDBX::AddEvent
0000000012AAED8D (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\db.cpp (352): db_event_add
000000001292936F (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\protocols.cpp (190): Proto_AuthRecv
0000000012929C02 (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\protocols.cpp (406): CallProtoServiceInt
000000001292B1A1 (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\proto_chains.cpp (131): Proto_ChainRecv
0000000012907FAE (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\ignore.cpp (405): IgnoreRecvAuth
0000000012AB56A3 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\modules.cpp (595): CallService
000000001292961F (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\protocols.cpp (460): ProtoCallService
0000000012929F7B (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\protocols.cpp (450): CallProtoServiceInt
000000001292B140 (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\proto_chains.cpp (114): Proto_ChainRecv
0000000012AB56A3 (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\modules.cpp (595): CallService
0000000012AB459E (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\modules.cpp (603): CallServiceToMainAPCFunc
0000000012AB406C (mir_core 0000000012AA0000): w:\miranda-build\src\mir_core\src\miranda.cpp (82): APCWndProc
00007FFBAF25BC50 (USER32 00007FFBAF250000): (filename not available) (0): CallWindowProcW
00007FFBAF25B5CF (USER32 00007FFBAF250000): (filename not available) (0): DispatchMessageW
0000000012917410 (mir_app 00000000128C0000): w:\miranda-build\src\mir_app\src\miranda.cpp (378): mir_main
0000000140002944 (Miranda64 0000000140000000): w:\miranda-build\src\miranda32\src\miranda.cpp (62): wWinMain
00000001400014BA (Miranda64 0000000140000000): f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl (288): __scrt_common_main_seh
00007FFBAF0F2784 (KERNEL32 00007FFBAF0E0000): (filename not available) (0): BaseThreadInitThunk
00007FFBB1B10C31 (ntdll 00007FFBB1AC0000): (filename not available) (0): RtlUserThreadStart
```

**Comment by georgehazan** [comment]
I can't reproduce the first problem... everything else fixed

**Comment by LittleVulpix** [comment]
@georgehazan as spoken via IM, I have given you various logs and reproduction scenarios for the issues; some have been fixed whilst others are still present.

Let me know when changes are pushed and I'll retest.

Thanks!

**Comment by LittleVulpix** [comment]
Continuation - now the import imports all the letters (yay, thanks @georgehazan ), but then trying to export the imported data results in empty text bodies being exported.

Also, during import of a larger history, miranda grew to ~1.5GB of RAM and then quietly disappeared/crashed (without a crash message).
