### ISSUE TITLE
HistoryPP requires mir_core.dll

### ISSUE THREAD

**Issue by xtemp09** [miranda-ng/miranda-ng#916]
Update to the stable version and update to the latest development version deletes mir_core.dll while it's required by HistoryPP.

The update causes crash without crash log if I try to get to the settings.

**Comment by Robyer** [comment]
mir_core.dll is deleted because it is replaced by mir_core.mir (different extension). Perhaps you have some old version of historypp?

**Comment by xtemp09** [comment]
Robyer, HistoryPP is being updated when Miranda updates.

**Comment by georgehazan** [comment]
not if you renamed it. you definitely have the old version of it, try to remove it and readd via Plugin Updater

**Comment by xtemp09** [comment]
Ok, I'll give it a try.

**Comment by xtemp09** [comment]
Updating of HistoryPP brings other problem, like "DLL entry point not found". So far I know that Miranda and its plugins completely changed inner API. It means partial update brings more troubles than full update. Full update makes IRC plugin non-working (Issue #915) and I don't know if the problem worked out since I don't have the latest development version.

So the only way here is to wait till the "stable" version becomes "stabler."

**Comment by georgehazan** [comment]
you cannot update one DLL only, all of them should be of the same build, #915 is already fixed and the correspondent nightly build uploaded this morning

**Comment by xtemp09** [comment]
Just updated till the latest development version. "History++ MainWindow: Miranda64.exe" "The program cannot run because of absence of mir_core.dll. Try to reinstall the program". If I press the "Ok" button ,the program runs, moreover, HistoryPP seems to work fine. I deleted the settings for the plugin, restarted, resaved the settings, the problem remain. Issue #915 seems to be solved.

Here goes the version info, I think it will help (I found "Plugin statically linked to missing module: mir_core.dll"):
CPU: AMD Phenom(tm) II X3 720 Processor [AMD64 Family 16 Model 4 Stepping 2] [DEP Enabled] [3 CPUs]
Installed RAM: 8189 MBytes
Microsoft Windows 7 Professional Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.18537 (build 99600)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Russian/Russian | Russian/Russian
Free disk space on Miranda partition: 4501 MBytes

Miranda NG Version: 0.95.7 alpha build #18482 (2bf6c99) x64
Build time: 5 Sep 2017 14:27:08
Profile: C:\Program Files\AMSMiranda\Profiles\AMS\AMS.dat (dbx mmap driver)
Profile size: 3538944 Bytes
Profile creation date: 5 Sep 2017 19:08:29
Language pack: Russian (RU) [0419]
Service Mode: No

Active Plugins (14):
¤ AdvaImg.dll v.0.11.0.2 [5 Sep 2017 14:27:58] - Miranda image services 
¤ AVS.dll v.0.95.3.4 [5 Sep 2017 14:27:10] - Avatar service 
¤ Clist_modern.dll v.0.9.1.6 [5 Sep 2017 14:27:36] - Modern contact list 
¤ CrashDumper.dll v.0.0.5.2 [5 Sep 2017 14:27:34] - Crash dumper 
¤ DbEditorPP.dll v.4.0.1.1 [5 Sep 2017 14:27:34] - Database editor++ 
¤ Dbx_mmap.dll v.0.95.3.1 [5 Sep 2017 14:27:12] - Miranda NG mmap database driver 
¤ HistoryPP.dll v.1.5.1.5 [6 Aug 2017 13:57:16] - History++ 
¤ ICQ.dll v.0.11.3.5 [5 Sep 2017 14:27:14] - IcqOscarJ protocol 
¤ IRC.dll v.0.11.0.3 [5 Sep 2017 14:27:12] - IRC protocol 
¤ PluginUpdater.dll v.0.1.2.5 [5 Sep 2017 14:27:38] - Plugin updater 
¤ Popup.dll v.2.1.1.12 [5 Sep 2017 14:27:22] - Popup plus 
¤ SkypeWeb.dll v.0.12.2.4 [5 Sep 2017 14:28:12] - Skype protocol (Web) 
¤ Spamotron.dll v.0.0.4.7 [5 Sep 2017 14:27:58] - Spam-o-tron 
¤ TabSRMM.dll v.3.5.0.6 [5 Sep 2017 14:27:18] - TabSRMM 

Unloadable Plugins (2):
¤ DbChecker.dll v.0.0.0.0 [5 Sep 2017 14:27:36] - <unknown> 

¤ KeepStatus.dll v.0.0.0.0 [1 Jan 2015 16:20:32] - <unknown> 
     **Plugin statically linked to missing module: mir_core.dll**


Protocols and Accounts:
-------------------------------------------------------------------------------
ICQ                      1 - Enabled 0 - Disabled  Loaded
IRC                      1 - Enabled 2 - Disabled  Loaded
SKYPE                    1 - Enabled 0 - Disabled  Loaded
JABBER                   0 - Enabled 1 - Disabled  Not Loaded
MetaContacts             1 - Enabled 0 - Disabled  Loaded
Weather                  0 - Enabled 1 - Disabled  Not Loaded

Icon Packs:
-------------------------------------------------------------------------------
 Ball-without_symbols.dll [4 Jul 2008 16:03:30]
 Fp_icons.dll [5 Sep 2017 14:29:00]
 HistoryPP_icons.dll [5 Sep 2017 14:29:00]
 penguins.dll [1 Oct 2007 15:37:22]
 Proto_ICQ.dll [5 Sep 2017 14:29:00]
 Proto_IRC.dll [5 Sep 2017 14:29:00]
 Proto_Jabber.dll [5 Sep 2017 14:29:00]
 Proto_MetaContacts.dll [5 Sep 2017 14:29:00]
 Proto_Skype.dll [5 Sep 2017 14:29:00]
 Proto_VKontakte.dll [5 Sep 2017 14:29:00]
 Proto_Weather.dll [5 Sep 2017 14:29:00]
 TabSRMM_icons.dll [5 Sep 2017 14:29:00]
 Toolbar_icons.dll [5 Sep 2017 14:29:00]
 xStatus_ICQ.dll [5 Sep 2017 14:29:00]
 xStatus_Jabber.dll [5 Sep 2017 14:29:00]

**Comment by georgehazan** [comment]
are there any dlls (mostly in the Plugins/ subfolder) other than listed above?
or, if you have a file manager, try to find string mir_core.dll in Miranda's folder

**Comment by xtemp09** [comment]
Directory of Miranda\Plugins:

05.09.2017  19:13    <DIR>          .
05.09.2017  19:13    <DIR>          ..
05.09.2017  14:27           708 608 AdvaImg.dll
05.09.2017  14:27            70 144 AVS.dll
05.09.2017  14:27           508 928 Clist_modern.dll
05.09.2017  14:27            62 464 CrashDumper.dll
05.09.2017  14:27            50 688 DbChecker.dll
05.09.2017  14:27           114 688 DbEditorPP.dll
05.09.2017  14:27            74 240 Dbx_mmap.dll
06.08.2017  13:57         3 133 952 HistoryPP.dll
05.09.2017  14:27           420 864 ICQ.dll
05.09.2017  14:27            47 104 Import.dll
05.09.2017  14:27           334 336 IRC.dll
05.09.2017  14:27           802 816 Jabber.dll
01.01.2015  16:20            61 440 KeepStatus.dll
05.09.2017  14:27            78 848 PluginUpdater.dll
05.09.2017  14:27           260 608 Popup.dll
05.09.2017  14:28           358 400 SkypeWeb.dll
05.09.2017  14:27           413 696 Spamotron.dll
05.09.2017  14:27           577 536 TabSRMM.dll
05.09.2017  14:27            47 616 TopToolBar.dll
              19 File(s)      8 126 976 bytes

"mir_core.dll" is only in "KeepStatus.dll", the profile.dat and in the crash logs.

**Comment by xtemp09** [comment]
What is the replacement for KeepStatus?

**Comment by georgehazan** [comment]
of 01.01.2015?! remove it
these status plugins were merged together into StatusManager plugin, you can install it via Plugin Updater

**Comment by xtemp09** [comment]
I've successfully updated Miranda to the latest development version. Deletion of KeepStatus caused crash of Miranda, so I've deleted it manually.

I found another thing - I tried to turn on or off AdvaImg, however, the checkbox disappears. I can turn it on or off with DBEditor, but it doesn't seem to affect the settings.

**Comment by georgehazan** [comment]
AdvaImg cannot be removed or disabled, because it's vitally important for the core services
